apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose-build.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose-build.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-user
    spec:
      containers:
        - image: efuraimujs/api-users-component:v1
          name: backend-user
          resources: {}
      restartPolicy: Always
status: {}
