apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose-build.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-feed
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose-build.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-feed
    spec:
      containers:
        - image: efuraimujs/api-feeds-component:v1
          name: backend-feed
          resources: {}
      restartPolicy: Always
status: {}
