version: "3"
services:
  
  backend-user:
    build:
      context: ./api-users-component
    image: efuraimujs/api-users-component:v1
  backend-feed:
    build:
      context: ./api-feeds-component
    image: efuraimujs/api-feeds-component:v1

  reverseproxy:
    build:
      context: ./api-gateway-component
    image: efuraimujs/api-gateway-component:v1
    
  frontend:
    build:
      context: ./frontend-component
    image: efuraimujs/frontend-component:v1