version: "3"
services:
  
  backend_user:
    build:
      context: ./api-users-component
    image: api-users-component:v1
  backend_feed:
    build:
      context: ./api-feeds-component
    image: api-feeds-component:v1

  reverseproxy:
    build:
      context: ./api-gateway-component
    image: api-gateway-component:v1
    
  frontend:
    build:
      context: ./frontend-component
    image: frontend-component:v1