version: "3"
services:
  backend_user:
    image: efuraimujs/api-users-component:v1
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # networks:
    #   - example-net

  backend_feed:
    image: efuraimujs/api-feeds-component:v1
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # networks:
    #   - example-net

  reverseproxy:
    image: api-gateway-component:v1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend_user
      - backend_feed
    # networks:
    #   - example-net
          
  frontend:
    image: frontend-component:v1
    ports:
      - "8100:80"
    # networks:
    #   - example-net

# networks:
#   example-net:
#     external: true