apiVersion: v1
kind: Service
metadata:
  labels:
    service: backenduser
  name: backenduser
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: backenduser
  type: ClusterIP